package com.example.core.exporter

import com.example.data.model.ChapterEntity
import com.example.data.model.GlossaryEntity
import com.example.data.model.ProjectEntity
import com.example.core.project.ProjectFileManager
import java.io.File

object TxtExporter {

    fun exportMergedTxt(
        project: ProjectEntity,
        chapters: List<ChapterEntity>,
        glossary: List<GlossaryEntity>,
        fileManager: ProjectFileManager,
        includeGlossaryAppendix: Boolean = false,
        includeOriginalParallel: Boolean = false
    ): File {
        val exportsDir = fileManager.getExportsDir(project.id)
        val sanitizedTitle = project.title.replace(Regex("[\\\\/:*?\"<>|]"), "_")
        val exportFile = File(exportsDir, "${sanitizedTitle}_translated.txt")

        val sb = StringBuilder()
        sb.append("=========================================\n")
        sb.append("《${project.title}》\n")
        sb.append("Author: ${project.author}\n")
        sb.append("Target Language: ${project.targetLanguage}\n")
        sb.append("Translated Chapters: ${chapters.count { it.translatedWordCount > 0 }} / ${chapters.size}\n")
        sb.append("Generated by: Novel Translator AI Studio\n")
        sb.append("=========================================\n\n\n")

        for (chapter in chapters) {
            sb.append("-----------------------------------------\n")
            sb.append("【${chapter.title}】\n")
            sb.append("-----------------------------------------\n\n")

            val translatedText = fileManager.readTranslatedChapter(project.id, chapter.translatedFileName)
            val originalText = fileManager.readOriginalChapter(project.id, chapter.originalFileName)

            if (includeOriginalParallel && originalText.isNotBlank()) {
                val origParagraphs = originalText.split(Regex("\n{2,}|\r\n\r\n"))
                val transParagraphs = (if (translatedText.isNotBlank()) translatedText else "[Pending Translation]").split(Regex("\n{2,}|\r\n\r\n"))
                val maxP = maxOf(origParagraphs.size, transParagraphs.size)

                for (i in 0 until maxP) {
                    val oP = origParagraphs.getOrNull(i) ?: ""
                    val tP = transParagraphs.getOrNull(i) ?: ""
                    if (oP.isNotBlank()) sb.append("[原文] ").append(oP.trim()).append("\n")
                    if (tP.isNotBlank()) sb.append("[译文] ").append(tP.trim()).append("\n\n")
                }
            } else {
                if (translatedText.isNotBlank()) {
                    sb.append(translatedText.trim())
                } else if (originalText.isNotBlank()) {
                    sb.append("[未翻译原文 / Untranslated Original]\n").append(originalText.trim())
                }
            }
            sb.append("\n\n\n")
        }

        if (includeGlossaryAppendix && glossary.isNotEmpty()) {
            sb.append("=========================================\n")
            sb.append("【附录：专有名词与术语表 / Glossary Appendix】\n")
            sb.append("=========================================\n\n")
            for (term in glossary) {
                sb.append("• [${term.category.label}] ${term.originalTerm}  ==>  ${term.translatedTerm}")
                if (term.notes.isNotBlank()) {
                    sb.append(" (${term.notes})")
                }
                sb.append("\n")
            }
        }

        exportFile.writeText(sb.toString(), Charsets.UTF_8)
        return exportFile
    }
}
